// data-testid values used by the SDK, imported straight from the ReScript
// build output (src/Utilities/TestUtils.res -> TestUtils.bs.js, generated by
// `npm run re:build` at the repo root; gitignored). Never copy these by hand.
//
//   import { testIds } from "../../fixtures";
//   sdk.field(testIds.cardNoInputTestId)
export * as testIds from "../../src/Utilities/TestUtils.bs.js";
