/*
 The payment-method field table, split out of PaymentMethodsRecord.res: PaymentMethodsRecord is
 imported by the loader entry, but these two fields are only called app-side (DynamicFields,
 PaymentOptions, AccordionContainer), so the lazy phone field - and with it Phone_number.json -
 never enters the loader's runtime.
 */
open PaymentMethodsRecord

let getPaymentMethodsFields = (~localeString: LocaleStringTypes.localeStrings) => [
  {
    paymentMethodName: "afterpay_clearpay",
    fields: [InfoElement],
    icon: Some(icon("afterpay", ~size=19)),
    displayName: localeString.payment_methods_afterpay_clearpay,
    miniIcon: None,
  },
  {
    paymentMethodName: "google_pay",
    fields: [InfoElement],
    icon: Some(icon("google_pay", ~size=19, ~width=25)),
    displayName: localeString.payment_methods_google_pay,
    miniIcon: None,
  },
  {
    paymentMethodName: "apple_pay",
    fields: [InfoElement],
    icon: Some(icon("apple_pay", ~size=19, ~width=25)),
    displayName: localeString.payment_methods_apple_pay,
    miniIcon: None,
  },
  {
    paymentMethodName: "mb_way",
    fields: [
      SpecialField(
        <ReusableReactSuspense
          loaderComponent={React.null} componentName="PhoneNumberPaymentInputLazy">
          <PhoneNumberPaymentInputLazy />
        </ReusableReactSuspense>,
      ),
      InfoElement,
    ],
    icon: Some(icon("mbway", ~size=19)),
    displayName: localeString.payment_methods_mb_way,
    miniIcon: None,
  },
  {
    paymentMethodName: "mobile_pay",
    fields: [InfoElement],
    icon: Some(icon("mobilepay", ~size=19)),
    displayName: localeString.payment_methods_mobile_pay,
    miniIcon: None,
  },
  {
    paymentMethodName: "ali_pay",
    fields: [InfoElement],
    icon: Some(icon("alipay", ~size=19)),
    displayName: localeString.payment_methods_ali_pay,
    miniIcon: None,
  },
  {
    paymentMethodName: "ali_pay_hk",
    fields: [InfoElement],
    icon: Some(icon("alipayhk", ~size=19)),
    displayName: localeString.payment_methods_ali_pay_hk,
    miniIcon: None,
  },
  {
    paymentMethodName: "we_chat_pay",
    fields: [InfoElement],
    icon: Some(icon("wechatpay", ~size=19)),
    displayName: localeString.payment_methods_we_chat_pay,
    miniIcon: None,
  },
  {
    paymentMethodName: "duit_now",
    fields: [InfoElement],
    icon: Some(icon("duitNow", ~size=20)),
    displayName: localeString.payment_methods_duit_now,
    miniIcon: None,
  },
  {
    paymentMethodName: "revolut_pay",
    fields: [InfoElement],
    icon: Some(icon("revolut", ~size=20)),
    displayName: localeString.payment_methods_revolut_pay,
    miniIcon: None,
  },
  {
    paymentMethodName: "affirm",
    fields: [InfoElement],
    icon: Some(icon("affirm", ~size=20)),
    displayName: localeString.payment_methods_affirm,
    miniIcon: None,
  },
  {
    paymentMethodName: "pay_safe_card",
    fields: [InfoElement],
    icon: Some(icon("pay_safe_card", ~size=19)),
    displayName: localeString.payment_methods_pay_safe_card,
    miniIcon: None,
  },
  {
    paymentMethodName: "crypto_currency",
    fields: [InfoElement],
    icon: Some(icon("crypto", ~size=19)),
    displayName: localeString.payment_methods_crypto_currency,
    miniIcon: None,
  },
  {
    paymentMethodName: "card",
    icon: Some(icon("default-card", ~size=19)),
    fields: [],
    displayName: localeString.payment_methods_card,
    miniIcon: None,
  },
  {
    paymentMethodName: "klarna",
    icon: Some(icon("klarna", ~size=19)),
    fields: [InfoElement],
    displayName: localeString.payment_methods_klarna,
    miniIcon: None,
  },
  {
    paymentMethodName: "sofort",
    icon: Some(icon("sofort", ~size=19)),
    fields: [InfoElement],
    displayName: localeString.payment_methods_sofort,
    miniIcon: None,
  },
  {
    paymentMethodName: "flexiti",
    icon: Some(icon("flexiti", ~size=19)),
    fields: [InfoElement],
    displayName: "Flixiti",
    miniIcon: None,
  },
  {
    paymentMethodName: "breadpay",
    icon: Some(icon("breadpay", ~size=19)),
    fields: [InfoElement],
    displayName: "Breadpay",
    miniIcon: None,
  },
  {
    paymentMethodName: "ach_transfer",
    icon: Some(icon("ach", ~size=19)),
    fields: [],
    displayName: localeString.payment_methods_ach_transfer,
    miniIcon: None,
  },
  {
    paymentMethodName: "bacs_transfer",
    icon: Some(icon("bank", ~size=19)),
    fields: [],
    displayName: localeString.payment_methods_bacs_transfer,
    miniIcon: None,
  },
  {
    paymentMethodName: "sepa_bank_transfer",
    icon: Some(icon("sepa", ~size=19)),
    fields: [],
    displayName: localeString.payment_methods_sepa_bank_transfer,
    miniIcon: None,
  },
  {
    paymentMethodName: "instant_bank_transfer",
    icon: Some(icon("bank", ~size=19)),
    fields: [],
    displayName: localeString.payment_methods_instant_bank_transfer,
    miniIcon: None,
  },
  {
    paymentMethodName: "instant_bank_transfer_finland",
    icon: Some(icon("bank", ~size=19)),
    fields: [],
    displayName: localeString.payment_methods_instant_bank_transfer_finland,
    miniIcon: None,
  },
  {
    paymentMethodName: "instant_bank_transfer_poland",
    icon: Some(icon("bank", ~size=19)),
    fields: [],
    displayName: localeString.payment_methods_instant_bank_transfer_poland,
    miniIcon: None,
  },
  {
    paymentMethodName: "sepa_debit",
    icon: Some(icon("sepa", ~size=19, ~width=25)),
    displayName: localeString.payment_methods_sepa_debit,
    fields: [],
    miniIcon: None,
  },
  {
    paymentMethodName: "giropay",
    icon: Some(icon("giropay", ~size=19, ~width=25)),
    displayName: localeString.payment_methods_giropay,
    fields: [InfoElement],
    miniIcon: None,
  },
  {
    paymentMethodName: "eps",
    icon: Some(icon("eps", ~size=19, ~width=25)),
    displayName: localeString.payment_methods_eps,
    fields: [InfoElement],
    miniIcon: None,
  },
  {
    paymentMethodName: "walley",
    icon: Some(icon("walley", ~size=19, ~width=25)),
    displayName: localeString.payment_methods_walley,
    fields: [InfoElement],
    miniIcon: None,
  },
  {
    paymentMethodName: "pay_bright",
    icon: Some(icon("paybright", ~size=19, ~width=25)),
    displayName: localeString.payment_methods_pay_bright,
    fields: [InfoElement],
    miniIcon: None,
  },
  {
    paymentMethodName: "ach_debit",
    icon: Some(icon("ach", ~size=19)),
    displayName: localeString.payment_methods_ach_debit,
    fields: [InfoElement],
    miniIcon: None,
  },
  {
    paymentMethodName: "bacs_debit",
    icon: Some(icon("bank", ~size=21)),
    displayName: localeString.payment_methods_bacs_debit,
    fields: [InfoElement],
    miniIcon: Some(icon("bank", ~size=19)),
  },
  {
    paymentMethodName: "becs_debit",
    icon: Some(icon("bank", ~size=21)),
    displayName: localeString.payment_methods_becs_debit,
    fields: [InfoElement],
    miniIcon: Some(icon("bank", ~size=19)),
  },
  {
    paymentMethodName: "blik",
    icon: Some(icon("blik", ~size=19, ~width=25)),
    displayName: localeString.payment_methods_blik,
    fields: [InfoElement],
    miniIcon: None,
  },
  {
    paymentMethodName: "trustly",
    icon: Some(icon("trustly", ~size=19, ~width=25)),
    displayName: localeString.payment_methods_trustly,
    fields: [InfoElement],
    miniIcon: None,
  },
  {
    paymentMethodName: "bancontact_card",
    icon: Some(icon("bancontact", ~size=19, ~width=25)),
    displayName: localeString.payment_methods_bancontact_card,
    fields: [InfoElement],
    miniIcon: None,
  },
  {
    paymentMethodName: "online_banking_czech_republic",
    icon: Some(icon("bank", ~size=19, ~width=25)),
    displayName: localeString.payment_methods_online_banking_czech_republic,
    fields: [Bank, InfoElement],
    miniIcon: None,
  },
  {
    paymentMethodName: "online_banking_slovakia",
    icon: Some(icon("bank", ~size=19, ~width=25)),
    displayName: localeString.payment_methods_online_banking_slovakia,
    fields: [Bank, InfoElement],
    miniIcon: None,
  },
  {
    paymentMethodName: "online_banking_finland",
    icon: Some(icon("bank", ~size=19, ~width=25)),
    displayName: localeString.payment_methods_online_banking_finland,
    fields: [Bank, InfoElement],
    miniIcon: None,
  },
  {
    paymentMethodName: "online_banking_poland",
    icon: Some(icon("bank", ~size=19, ~width=25)),
    displayName: localeString.payment_methods_online_banking_poland,
    fields: [Bank, InfoElement],
    miniIcon: None,
  },
  {
    paymentMethodName: "ideal",
    icon: Some(icon("ideal_wero", ~size=19, ~width=25)),
    displayName: localeString.payment_methods_ideal,
    fields: [InfoElement],
    miniIcon: None,
  },
  {
    paymentMethodName: "ban_connect",
    icon: None,
    displayName: localeString.payment_methods_ban_connect,
    fields: [],
    miniIcon: None,
  },
  {
    paymentMethodName: "ach_bank_debit",
    icon: Some(icon("ach-bank-debit", ~size=19, ~width=25)),
    displayName: localeString.payment_methods_ach_bank_debit,
    fields: [],
    miniIcon: None,
  },
  {
    paymentMethodName: "przelewy24",
    icon: Some(icon("p24", ~size=19)),
    displayName: localeString.payment_methods_przelewy24,
    fields: [Email, Bank, InfoElement],
    miniIcon: None,
  },
  {
    paymentMethodName: "interac",
    icon: Some(icon("interac", ~size=19)),
    displayName: localeString.payment_methods_interac,
    fields: [InfoElement],
    miniIcon: None,
  },
  {
    paymentMethodName: "twint",
    icon: Some(icon("twint", ~size=19)),
    displayName: localeString.payment_methods_twint,
    fields: [InfoElement],
    miniIcon: None,
  },
  {
    paymentMethodName: "vipps",
    icon: Some(icon("vipps", ~size=19)),
    displayName: localeString.payment_methods_vipps,
    fields: [InfoElement],
    miniIcon: None,
  },
  {
    paymentMethodName: "dana",
    icon: Some(icon("dana", ~size=19)),
    displayName: localeString.payment_methods_dana,
    fields: [InfoElement],
    miniIcon: None,
  },
  {
    paymentMethodName: "go_pay",
    icon: Some(icon("go_pay", ~size=19)),
    displayName: localeString.payment_methods_go_pay,
    fields: [InfoElement],
    miniIcon: None,
  },
  {
    paymentMethodName: "kakao_pay",
    icon: Some(icon("kakao_pay", ~size=19)),
    displayName: localeString.payment_methods_kakao_pay,
    fields: [InfoElement],
    miniIcon: None,
  },
  {
    paymentMethodName: "gcash",
    icon: Some(icon("gcash", ~size=19)),
    displayName: localeString.payment_methods_gcash,
    fields: [InfoElement],
    miniIcon: None,
  },
  {
    paymentMethodName: "momo",
    icon: Some(icon("momo", ~size=19)),
    displayName: localeString.payment_methods_momo,
    fields: [InfoElement],
    miniIcon: None,
  },
  {
    paymentMethodName: "touch_n_go",
    icon: Some(icon("touch_n_go", ~size=19)),
    displayName: localeString.payment_methods_touch_n_go,
    fields: [InfoElement],
    miniIcon: None,
  },
  {
    paymentMethodName: "bizum",
    icon: Some(icon("bizum", ~size=19)),
    displayName: localeString.payment_methods_bizum,
    fields: [InfoElement],
    miniIcon: None,
  },
  {
    paymentMethodName: "classic",
    icon: Some(icon("cash_voucher", ~size=19, ~width=50)),
    displayName: localeString.payment_methods_classic,
    fields: [InfoElement],
    miniIcon: Some(icon("cash_voucher", ~size=19)),
  },
  {
    paymentMethodName: "online_banking_fpx",
    icon: Some(icon("online_banking_fpx", ~size=19)),
    displayName: localeString.payment_methods_online_banking_fpx,
    fields: [Bank, InfoElement], // add more fields for these payment methods
    miniIcon: None,
  },
  {
    paymentMethodName: "online_banking_thailand",
    icon: Some(icon("online_banking_thailand", ~size=19)),
    displayName: localeString.payment_methods_online_banking_thailand,
    fields: [Bank, InfoElement], // add more fields for these payment methods
    miniIcon: None,
  },
  {
    paymentMethodName: "alma",
    icon: Some(icon("alma", ~size=19)),
    displayName: localeString.payment_methods_alma,
    fields: [InfoElement],
    miniIcon: None,
  },
  {
    paymentMethodName: "atome",
    icon: Some(icon("atome", ~size=19)),
    displayName: localeString.payment_methods_atome,
    fields: [InfoElement],
    miniIcon: None,
  },
  {
    paymentMethodName: "multibanco_transfer",
    icon: Some(icon("multibanco", ~size=19)),
    displayName: localeString.payment_methods_multibanco_transfer,
    fields: [InfoElement],
    miniIcon: None,
  },
  {
    paymentMethodName: "card_redirect",
    icon: Some(icon("default-card", ~size=19)),
    displayName: localeString.payment_methods_card_redirect,
    fields: [InfoElement],
    miniIcon: None,
  },
  {
    paymentMethodName: "open_banking_uk",
    icon: Some(icon("bank", ~size=19)),
    displayName: localeString.payment_methods_pay_by_bank,
    fields: [InfoElement],
    miniIcon: Some(icon("bank", ~size=19)),
  },
  {
    paymentMethodName: "open_banking_pis",
    icon: Some(icon("bank", ~size=19)),
    displayName: localeString.payment_methods_open_banking_pis,
    fields: [InfoElement],
    miniIcon: Some(icon("bank", ~size=19)),
  },
  {
    paymentMethodName: "evoucher",
    icon: Some(icon("cash_voucher", ~size=19, ~width=50)),
    displayName: localeString.payment_methods_evoucher,
    fields: [InfoElement],
    miniIcon: Some(icon("cash_voucher", ~size=19)),
  },
  {
    paymentMethodName: "pix_transfer",
    fields: [InfoElement],
    icon: Some(icon("pix", ~size=26, ~width=40)),
    displayName: localeString.payment_methods_pix_transfer,
    miniIcon: None,
  },
  {
    paymentMethodName: "pix_emv_transfer",
    fields: [InfoElement],
    icon: Some(icon("pix", ~size=26, ~width=40)),
    displayName: localeString.payment_methods_pix_emv_transfer,
    miniIcon: None,
  },
  {
    paymentMethodName: "boleto",
    icon: Some(icon("boleto", ~size=21, ~width=25)),
    displayName: localeString.payment_methods_boleto,
    fields: [InfoElement],
    miniIcon: None,
  },
  {
    paymentMethodName: "paypal",
    icon: Some(icon("paypal", ~size=21, ~width=25)),
    displayName: localeString.payment_methods_paypal,
    fields: [InfoElement],
    miniIcon: None,
  },
  {
    paymentMethodName: "local_bank_transfer_transfer",
    fields: [InfoElement],
    icon: Some(icon("union-pay", ~size=19, ~width=30)),
    displayName: localeString.payment_methods_local_bank_transfer_transfer,
    miniIcon: None,
  },
  {
    paymentMethodName: "mifinity",
    fields: [InfoElement],
    icon: Some(icon("mifinity")),
    displayName: localeString.payment_methods_mifinity,
    miniIcon: None,
  },
  {
    paymentMethodName: "skrill",
    fields: [InfoElement],
    icon: Some(icon("skrill", ~size=19)),
    displayName: "Skrill",
    miniIcon: None,
  },
  {
    paymentMethodName: "bluecode",
    fields: [InfoElement],
    icon: Some(icon("bluecode")),
    displayName: "Bluecode",
    miniIcon: None,
  },
  {
    paymentMethodName: "upi_collect",
    fields: [InfoElement],
    icon: Some(icon("bhim_upi", ~size=19)),
    displayName: localeString.payment_methods_upi_collect,
    miniIcon: None,
  },
  {
    paymentMethodName: "upi_intent",
    fields: [InfoElement],
    icon: Some(icon("bhim_upi", ~size=19)),
    displayName: "UPI Intent",
    miniIcon: None,
  },
  {
    paymentMethodName: "eft",
    icon: Some(icon("eft", ~size=19)),
    fields: [InfoElement],
    displayName: localeString.payment_methods_eft,
    miniIcon: None,
  },
  {
    paymentMethodName: "givex",
    icon: Some(icon("givex", ~size=19, ~width=25)),
    displayName: localeString.payment_methods_givex,
    fields: [InfoElement],
    miniIcon: None,
  },
  {
    paymentMethodName: "open_banking",
    icon: Some(icon("bank", ~size=19)),
    displayName: localeString.payment_methods_pay_by_bank,
    fields: [InfoElement],
    miniIcon: Some(icon("bank", ~size=19)),
  },
  {
    paymentMethodName: "saved_methods",
    icon: Some(icon("default-card", ~size=19)),
    fields: [],
    displayName: localeString.payment_methods_saved_methods,
    miniIcon: None,
  },
]

let getPaymentDetails = (arr: array<string>, ~localeString) => {
  let finalArr = []
  let paymentMethodsFields = getPaymentMethodsFields(~localeString)
  arr
  ->Array.map(item => {
    let optionalVal = paymentMethodsFields->Array.find(i => i.paymentMethodName == item)
    switch optionalVal {
    | Some(val) => finalArr->Array.push(val)->ignore
    | None => ()
    }
  })
  ->ignore
  finalArr
}
