name: Check for Label

on:
  issues:
    types: [labeled]

jobs:
  check-label:
    runs-on: ubuntu-latest
    steps:
      - name: Check if label exists
        id: check_label
        uses: actions/github-script@v6
        with:
          script: |
            const label = 'your-label-name';
            const labels = context.payload.issue.labels.map(l => l.name);
            return labels.includes(label);

      - name: Set output
        id: set_output
        run: echo "LABEL_EXISTS=${{ steps.check_label.outputs.result }}" >> $GITHUB_ENV

      - name: Label exists
        if: env.LABEL_EXISTS == 'true'
        run: echo "Label exists."

      - name: Label does not exist
        if: env.LABEL_EXISTS == 'false'
        run: echo "Label does not exist."
