name: Check for Label

on:
  pull_request_target:
    types:
      - opened
      - edited
      - reopened
      - ready_for_review
      - synchronize

jobs:
  check-label:
    runs-on: ubuntu-latest
    steps:
      - name: Check if label exists
        id: check_label
        uses: actions/github-script@v6
        with:
          script: |
            const label = 'your-label-name';
            console.log(`Looking for label: ${label}`);

            const labels = context.payload.pull_request.labels.map(l => l.name);
            console.log('Labels on this pull request:', labels);

            const labelExists = labels.includes(label);
            console.log(`Does the label "${label}" exist?`, labelExists);

            return labelExists;

      - name: Set output
        run: echo "LABEL_EXISTS=${{ steps.check_label.outputs.result }}" >> $GITHUB_ENV

      - name: Label exists
        if: env.LABEL_EXISTS == 'true'
        run: echo "Label exists."

      - name: Label does not exist
        if: env.LABEL_EXISTS == 'false'
        run: echo "Label does not exist."
