name: PR Title Spell Check

on:
  merge_group:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  typos:
    name: Spell check PR title
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Store PR title in a file
        shell: bash
        env:
          TITLE: ${{ github.event.pull_request.title }}
        run: echo $TITLE > pr_title.txt

      - name: Spell check
        uses: crate-ci/typos@master
        with:
          files: ./pr_title.txt

      - name: Assign to author
        run: |
          PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")

          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/${GITHUB_REPOSITORY}/issues/${PR_NUMBER}/assignees \
          -d '{"assignees":["${{ github.event.pull_request.user.login }}"]}'
