name: PR Validations

on:
  merge_group:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  typos:
    name: Spell check PR title
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Store PR title in a file
        shell: bash
        env:
          TITLE: ${{ github.event.pull_request.title }}
        run: echo $TITLE > pr_title.txt

      - name: Spell check
        uses: crate-ci/typos@master
        with:
          files: ./pr_title.txt

  check-assignee:
    name: Check assignee
    runs-on: ubuntu-latest
    steps:
      - name: Check assignee
        run: |
          response=$(curl -L \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/${{ github.repository }}/assignees)

          echo "$response" > response.log
