name: Stable Release

on:
  workflow_dispatch:
    inputs:
      version_mode:
        description: "Version mode"
        required: true
        default: "auto"
        type: choice
        options:
          - auto
          - custom
      version_type:
        description: "Auto-bump type (patch/minor/major)"
        required: false
        default: "patch"
        type: choice
        options:
          - patch
          - minor
          - major
      stable_version:
        description: "Custom version number (e.g., 1.2.3) (only used in custom mode)"
        required: false
        type: string

jobs:
  create-version-bump-pr:
    runs-on: ubuntu-latest
    name: Create Version Bump PR
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Check admin permissions
        uses: actions/github-script@v7
        with:
          script: |
            try {
              // Get the user who triggered the workflow
              const actor = context.actor;
              console.log(`🔍 Checking permissions for user: ${actor}`);
              
              // Check if the user has admin permissions
              const { data: permission } = await github.rest.repos.getCollaboratorPermissionLevel({
                owner: context.repo.owner,
                repo: context.repo.repo,
                username: actor
              });
              
              console.log(`📋 User permission level: ${permission.permission}`);
              
              // Allow admin and maintain permissions
              const allowedPermissions = ['admin', 'maintain'];
              
              if (!allowedPermissions.includes(permission.permission)) {
                console.log(`❌ Access denied for user: ${actor}`);
                console.log(`   Required permission: admin or maintain`);
                console.log(`   Current permission: ${permission.permission}`);
                
                core.setFailed(`🚫 Access Denied: Only repository admins can run this workflow. Your permission level: ${permission.permission}`);
                return;
              }
              
              console.log(`✅ Access granted for user: ${actor} (${permission.permission})`);
              
            } catch (error) {
              console.log(`❌ Error checking permissions: ${error.message}`);
              core.setFailed(`🚫 Permission check failed: ${error.message}`);
            }

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ github.token }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Validate and process version
        id: version
        run: |
          # Get current version from package.json
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          echo "current_version=$CURRENT_VERSION" >> $GITHUB_OUTPUT
          echo "📋 Current version: $CURRENT_VERSION"

          # Function to bump version
          bump_version() {
            local version=$1
            local type=$2
            
            IFS='.' read -ra VERSION_PARTS <<< "$version"
            local major=${VERSION_PARTS[0]}
            local minor=${VERSION_PARTS[1]}
            local patch=${VERSION_PARTS[2]}
            
            case $type in
              "major")
                major=$((major + 1))
                minor=0
                patch=0
                ;;
              "minor")
                minor=$((minor + 1))
                patch=0
                ;;
              "patch")
                patch=$((patch + 1))
                ;;
            esac
            
            echo "$major.$minor.$patch"
          }

          # Function to compare versions (returns 0 if new_version >= current_version, 1 if new_version < current_version)
          is_version_valid() {
            local new_version=$1
            local current_version=$2
            
            echo "🔍 Debug: Comparing versions - new: $new_version, current: $current_version"
            
            # Split versions into arrays
            IFS='.' read -ra NEW_PARTS <<< "$new_version"
            IFS='.' read -ra CURRENT_PARTS <<< "$current_version"
            
            # Compare major, minor, patch
            for i in 0 1 2; do
              local new_part=${NEW_PARTS[$i]:-0}
              local current_part=${CURRENT_PARTS[$i]:-0}
              
              echo "🔍 Debug: Comparing part $i - new: $new_part, current: $current_part"
              
              if [ "$new_part" -gt "$current_part" ]; then
                echo "🔍 Debug: New version is higher (part $i: $new_part > $current_part)"
                return 0  # new_version > current_version (valid)
              elif [ "$new_part" -lt "$current_part" ]; then
                echo "🔍 Debug: New version is lower (part $i: $new_part < $current_part)"
                return 1  # new_version < current_version (invalid)
              fi
              # If equal, continue to next part
            done
            
            echo "🔍 Debug: Versions are equal"
            return 0  # new_version == current_version (valid)
          }

          # Determine version based on mode
          VERSION_MODE="${{ github.event.inputs.version_mode }}"

          echo "🔍 Debug: VERSION_MODE = '$VERSION_MODE'"
          echo "🔍 Debug: Custom version input = '${{ github.event.inputs.stable_version }}'"

          if [ "$VERSION_MODE" = "auto" ]; then
            # Auto-bump version
            VERSION_TYPE="${{ github.event.inputs.version_type }}"
            NEW_VERSION=$(bump_version "$CURRENT_VERSION" "$VERSION_TYPE")
            echo "🔄 Auto-bumping $VERSION_TYPE version: $CURRENT_VERSION → $NEW_VERSION"
          elif [ "$VERSION_MODE" = "custom" ]; then
            # Custom version
            NEW_VERSION="${{ github.event.inputs.stable_version }}"
            
            echo "🔍 Debug: Processing custom version: '$NEW_VERSION'"
            
            if [ -z "$NEW_VERSION" ] || [ "$NEW_VERSION" = "null" ]; then
              echo "❌ VALIDATION FAILED: Custom version cannot be empty when mode is 'custom'"
              echo "   Please provide a valid version number (e.g., 1.2.3)"
              echo "🚫 Workflow stopped due to validation failure."
              exit 1
            fi
            
            # Validate version format (basic semver check)
            if ! [[ "$NEW_VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
              echo "❌ VALIDATION FAILED: Invalid version format: '$NEW_VERSION'"
              echo "   Version must follow semantic versioning format (e.g., 1.2.3)"
              echo "🚫 Workflow stopped due to validation failure."
              exit 1
            fi
            
            echo "🔍 Debug: About to validate version comparison..."
            
            # Check if new version is not lower than current version
            if is_version_valid "$NEW_VERSION" "$CURRENT_VERSION"; then
              echo "✅ Validation passed: Using custom version: $CURRENT_VERSION → $NEW_VERSION"
            else
              echo "❌ VALIDATION FAILED: Custom version $NEW_VERSION is LOWER than current version $CURRENT_VERSION"
              echo "   New version must be equal to or higher than the current version"
              echo "   Current: $CURRENT_VERSION"
              echo "   Provided: $NEW_VERSION"
              echo "   Please provide a version >= $CURRENT_VERSION"
              echo ""
              echo "🚫 Workflow stopped due to validation failure. No PR will be created."
              exit 1
            fi
          else
            echo "❌ VALIDATION FAILED: Invalid version mode: '$VERSION_MODE'"
            echo "   Valid modes are: 'auto' or 'custom'"
            echo "🚫 Workflow stopped due to validation failure."
            exit 1
          fi

          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT
          echo "✅ Version will be bumped from $CURRENT_VERSION to $NEW_VERSION"

      - name: Update package.json version and regenerate lock file
        run: |
          NEW_VERSION="${{ steps.version.outputs.new_version }}"

          # Update package.json
          node -e "
            const fs = require('fs');
            const pkg = require('./package.json');
            pkg.version = '$NEW_VERSION';
            fs.writeFileSync('./package.json', JSON.stringify(pkg, null, 2) + '\n');
          "

          echo "✅ Updated package.json to version $NEW_VERSION"

          # Regenerate package-lock.json
          npm install --package-lock-only
          echo "🔄 Regenerated package-lock.json"

      - name: Create version bump branch and commit
        id: version_bump
        run: |
          NEW_VERSION="${{ steps.version.outputs.new_version }}"
          BRANCH_NAME="release/bump-version-to-$NEW_VERSION"

          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

          # Check if branch exists remotely and delete it
          if git ls-remote --exit-code --heads origin "$BRANCH_NAME" >/dev/null 2>&1; then
            echo "🗑️ Branch $BRANCH_NAME already exists remotely, deleting it"
            git push origin --delete "$BRANCH_NAME" || true
          fi

          # Check if branch exists locally and delete it
          if git show-ref --verify --quiet "refs/heads/$BRANCH_NAME"; then
            echo "🗑️ Branch $BRANCH_NAME exists locally, deleting it"
            git branch -D "$BRANCH_NAME" || true
          fi

          # Create and switch to new branch
          git checkout -b "$BRANCH_NAME"

          # Add both package.json and package-lock.json
          git add package.json package-lock.json
          git commit -m "chore: bump version to $NEW_VERSION"
          git push origin "$BRANCH_NAME"

          echo "branch_name=$BRANCH_NAME" >> $GITHUB_OUTPUT
          echo "✅ Created branch $BRANCH_NAME and committed version bump (package.json + package-lock.json)"

      - name: Create Pull Request
        id: cpr
        continue-on-error: true
        uses: actions/github-script@v7
        with:
          script: |
            const newVersion = '${{ steps.version.outputs.new_version }}';
            const branchName = '${{ steps.version_bump.outputs.branch_name }}';
            const repoUrl = `https://github.com/${{ github.repository }}`;
            const prUrl = `${repoUrl}/compare/main...${branchName}?expand=1`;

            const prBody = `## Version Bump to ${newVersion}

            This PR bumps the version from ${{ steps.version.outputs.current_version }} to ${newVersion}.

            **Changes:**
            - Updated \`package.json\` version field
            - Updated \`package-lock.json\` with new version

            This PR was automatically created by the stable release workflow.

            **Next Steps:**
            1. Review and merge this PR
            2. Manually create the release and tag from the main branch after merging`;

            try {
              // Try to create PR automatically
              const pr = await github.rest.pulls.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: `release: v${newVersion}`,
                head: branchName,
                base: 'main',
                body: prBody
              });

              console.log(`✅ Successfully created PR automatically: ${pr.data.html_url}`);

              // Set outputs for success case
              core.setOutput('pull-request-number', pr.data.number);
              core.setOutput('pull-request-url', pr.data.html_url);
              core.setOutput('pull-request-operation', 'created');
              core.setOutput('pull-request-branch', branchName);

            } catch (error) {
              console.log(`⚠️ Failed to create PR automatically: ${error.message}`);
              console.log(`🔗 Create PR manually at: ${prUrl}`);

              // Set outputs for failure case
              core.setOutput('pull-request-number', '');
              core.setOutput('pull-request-url', '');
              core.setOutput('pull-request-operation', 'failed');
              core.setOutput('pull-request-branch', branchName);
            }

      - name: Display Results and Next Steps
        uses: actions/github-script@v7
        with:
          script: |
            const newVersion = '${{ steps.version.outputs.new_version }}';
            const prNumber = '${{ steps.cpr.outputs.pull-request-number }}';
            const prUrl = '${{ steps.cpr.outputs.pull-request-url }}';
            const prOperation = '${{ steps.cpr.outputs.pull-request-operation }}';
            const branchName = '${{ steps.cpr.outputs.pull-request-branch }}' || `release/bump-version-to-${newVersion}`;
            const repoUrl = `https://github.com/${{ github.repository }}`;
            const manualPrUrl = `${repoUrl}/compare/main...${branchName}?expand=1`;

            const prBody = `## Version Bump to ${newVersion}

            This PR bumps the version from ${{ steps.version.outputs.current_version }} to ${newVersion}.

            **Changes:**
            - Updated \`package.json\` version field  
            - Updated \`package-lock.json\` with new version

            This PR was created following the stable release workflow.

            **Next Steps:**
            1. Review and merge this PR
            2. Manually create the release and tag from the main branch after merging`;

            if (prNumber) {
              console.log(`✅ Successfully ${prOperation} PR #${prNumber}: ${prUrl}`);
              
              // Success summary
              core.summary
                .addHeading('🎉 Version Bump PR Created Successfully')
                .addTable([
                  [{data: 'Previous Version', header: true}, {data: 'New Version', header: true}, {data: 'PR Number', header: true}, {data: 'Files Updated', header: true}],
                  ['${{ steps.version.outputs.current_version }}', newVersion, `#${prNumber}`, 'package.json + package-lock.json']
                ])
                .addLink('View Pull Request', prUrl)
                .addHeading('📋 Next Steps')
                .addList([
                  'Review and merge the PR above',
                  'After merging, manually create the release and tag from the main branch'
                ])
                .addRaw('<br><br>**Note:** This workflow only creates the version bump PR. Release creation is manual.')
                .write();
            } else {
              console.log(`⚠️ Automatic PR creation failed`);
              console.log(`🔗 Create PR manually at: ${manualPrUrl}`);
              
              // Fallback summary with manual instructions
              core.summary
                .addHeading('📋 Version Bump Changes Ready')
                .addTable([
                  [{data: 'Previous Version', header: true}, {data: 'New Version', header: true}, {data: 'Branch', header: true}, {data: 'Files Updated', header: true}],
                  ['${{ steps.version.outputs.current_version }}', newVersion, branchName, 'package.json + package-lock.json']
                ])
                .addHeading('⚠️ Automatic PR Creation Failed')
                .addRaw(`<p><strong>Reason:</strong> The automatic PR creation failed.</p>`)
                .addHeading('🔧 How to Enable Automatic PR Creation')
                .addRaw(`<p>To enable automatic PR creation, you have several options:</p>`)
                .addList([
                  '**Option 1:** Go to Settings → Actions → General → Workflow permissions → Check "Allow GitHub Actions to create and approve pull requests"',
                  '**Option 2:** Create a Personal Access Token (PAT) with repo permissions and add it as GH_PAT secret',
                  '**Option 3:** Use the manual PR creation below (current fallback)'
                ])
                .addHeading('🔗 Create Pull Request Manually')
                .addRaw(`<p><strong>Changes are ready!</strong> Please create the PR manually using the link below.</p>`)
                .addLink('Click here to create the PR', manualPrUrl)
                .addHeading('📝 Suggested PR Details')
                .addRaw(`<p><strong>Title:</strong> <code>release: v${newVersion}</code></p>`)
                .addRaw(`<p><strong>Description:</strong></p>`)
                .addCodeBlock(prBody, 'markdown')
                .addHeading('📋 Next Steps After PR Creation')
                .addList([
                  'Review and merge the PR',
                  'After merging, manually create the release and tag from the main branch'
                ])
                .addRaw('<br><br>**Note:** This workflow only creates the version bump PR. Release creation is manual.')
                .write();
            }
